export const deviceArr = [
    {
        Type : "Device",
        Mac : "DC:4F:22:5F:65:76",
        Host_Name : "",
        SSID : "HUE_DEVICE_01",
        IP_Address : "192.168.1.70",
        Last_WS_Msg_Sent_Time_Stamp : 0,
        Last_WS_Msg_Received_Time_Stam : 0,
        Last_Heart_Time_Stamp : 0,
        Connected : false,
        Last_State : "#637AFF",
        Dashoard_Type : "",
    },
    {
        Type : "Device",
        Mac : "2C:F4:32:57:74:00",
        Host_Name : "",
        SSID : "HUE_DEVICE_02",
        IP_Address : "192.168.4.1",
        Last_WS_Msg_Sent_Time_Stamp : 0,
        Last_WS_Msg_Received_Time_Stam : 0,
        Last_Heart_Time_Stamp : 0,
        Connected : false,
        Last_State : "#90ee90",
        Dashoard_Type : "",
    },
    // {
    //     Type : "Device",
    //     Mac : "DC:4F:22:5F:63:EC",
    //     Host_Name : "",
    //     SSID : "Homelink1",
    //     IP_Address : "192.168.1.72",
    //     Last_WS_Msg_Sent_Time_Stamp : 0,
    //     Last_WS_Msg_Received_Time_Stam : 0,
    //     Last_Heart_Time_Stamp : 0,
    //     Connected : false,
    //     Last_State : "#637AFF",
    //     Dashoard_Type : "",
    // }
]